### PR TITLE
Remove blank space when simulating individual ccds

### PR DESCRIPTION
**Pull request by bojobo**

### CODE REVIEW

**Comment by bojobo** [comment]
(Branch has been rebased on #16)

**Comment by bojobo** [comment]
Final images with `sim_seperate_ccds = False`:

EMOS1:
image

EMOS2:
image

EPN:
image

**Comment by bojobo** [comment]
Images with `sim_seperate_ccds = True`

EMOS1:
image

EMOS2:
image

EPN:
image

**Review by SamSweere — APPROVED** [review]
Looks good, I don't have time to study every change. One observation. For the EPN images the two rows of ccd's do not seem to be aligned. This is a problem I had as well and did not find an easy fix for before switching to full frame. 
The verification of these simulations is quite important, I would highly recommend doing this in detail (and document it!)

**Review by SamSweere — APPROVED** [review]

**Comment by bojobo** [comment]
I know that they are misaligned, but that's how the CCDs are defined by the corresponding CCFs. While investigating the files a few months ago I've already noticed that the center (given by the distance from the center of the telescope in mm) of the CCDs do not align properly. Since these values are given by the team at ESA, I won't align the CCDs manually.

**Pull request merged**
